name: resume
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  url_launcher: ^6.1.6
  mailto: ^2.0.0
  screenshot: ^1.2.3
  pdf: ^3.8.4
  open_file_plus: ^3.3.0
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.1
  save:
    git:
      url: https://github.com/junhaotang0913/flutter-save-package.git
      ref: main
  json_theme: ^4.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true
